# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# https://subhankarsarkar.com/dot-net6-azure-web-app-deployment-using-azure-devops-pipeline/

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'
  targetRuntime: 'linux-x64'

steps:

- checkout: self
  displayName: 'Git Checkout, including submodules.'
  submodules: true

- task: UseDotNet@2
  displayName: 'Set .NET Version'
  inputs:
    version: $(dotNetVersion)
    includePreviewVersions: true

- task: NuGetCommand@2
  displayName: 'NuGet Restore Packages'
  inputs:
    restoreSolution: '**\*.sln'

- task: CmdLine@2
  displayName: Display Source Directory Content
  inputs:
    script: 'tree $(Build.SourcesDirectory) /f' 

# Build the Microservce
- task: DotNetCoreCLI@2
  displayName: 'Build the solution'
  inputs:
    command: 'build' 
    projects: 'Distro.Ordering.Microservice.sln'

# Publish it as .NET 6 self-contained application for linux runtime
- task: DotNetCoreCLI@2
  displayName: 'Publish the built project'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --runtime $(targetRuntime) --self-contained --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True